package models

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
)

//all data points that we'll send are pointers
//it's just a good practice
// ID will be generated by system so no pointer for it

type Entry struct {
	ID          primitive.ObjectID `bson:"id"`
	Dish        *string            `json:"dish"`
	Fat         *float64           `json:"fat"`
	Ingredients *string            `json:"ingredients"`
	Calories    *string            `json:"calories"`
}
